### ISSUE TITLE
Not picking up the params in a URL

### ISSUE THREAD

**Issue by anasqvik** [rduldulao/tornado-swirl#27]
For some reason, it's unable to pick the optional query param from the defined URL. How could this be solved? I'm not sure what I'm doing wrong, or what I'm missing here.

I've changed the pattern and even used the exact one used in the docs and tut.

```python
import tornado.web
import tornado_swirl as swirl

from .base import BaseHandler

@swirl.restapi('/item/(?P<id>[\w-]+)?')
class ItemHandler(BaseHandler):
    def post(self, id):
        """Item

        Creating a new item

        Tags:
            Item
        """
        # store the item
        pass

     async def get(self, id):
        """Item

        Get items or item

        Tags:
            Item
        """
        # return all items if no id was provided
        # or return item by id when provided
        pass
```

I'm getting the following error:

```bash
Traceback (most recent call last):
  File "/Users/.../venv/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/.../venv/lib/python3.7/site-packages/tornado_swirl/views.py", line 101, in get
    for path, spec, operations in apis},
  File "/Users/.../venv/lib/python3.7/site-packages/tornado_swirl/views.py", line 100, in <dictcomp>
    'paths': {path: self.__get_api_spec(spec, operations)
  File "/Users/.../venv/lib/python3.7/site-packages/tornado_swirl/views.py", line 368, in find_api
    ['{%s}' % arg for arg in [param.name for param in vals]]
TypeError: not enough arguments for format string
```

Apparently, it's not getting the arguments. I think it has something to do with how I'm defining the URL there?

The [question on Stackoverflow](https://stackoverflow.com/questions/56884262/tornado-swirl-not-picking-up-the-params-in-a-url)

**Comment by ovitaliw** [comment]
You just need to inform the path parameter in the docstring, something like that:

"""Item

Creating a new item

Path Params:
    id (string) --  Your id

Tags:
    Item
"""
